syntax = "proto3";
import "metadata.proto";

enum AtlasOperation {
  HANDSHAKE = 0;
  P_BIGBANG = 1;
  P_ARMAGEDDON = 2;
  P_OPENRW = 3;
  P_PEEK = 4;
  P_POKE = 5;
  P_RM = 6;
  P_MKDIR = 7;
  P_RMDIR = 8;
  P_RENAME = 9;
  P_COPY = 10;
  P_MOVE = 11;
}

message Meta {
  AtlasOperation op = 1;
  uint64 page_no = 2;
  uint32 offset = 3;
  uint32 length = 4;
  uint32 chunk_seq = 5;
  uint32 total_chunks = 6;
}

message BigBangData {
  FileSystemRecord fs_record=1;
}

message ArmageddonData {
  FileSystemRecord fs_record=1;
}

message Packet {
  Meta meta = 1;
  oneof data {
    bytes raw_data = 2;
    BigBangData bigbang_data = 3;
    ArmageddonData armageddon_data = 4;
  }
}