syntax = "proto3";
import "metadata.proto";

enum AtlasOperation {
  HANDSHAKE = 0;
  P_BIGBANG = 1;
  P_ARMAGEDDON = 2;
  P_OPENRW = 3;
  P_PEEK = 4;
  P_POKE = 5;
  P_RM = 6;
  P_MKDIR = 7;
  P_RMDIR = 8;
  P_RENAME = 9;
  P_COPY = 10;
  P_MOVE = 11;
  P_QUORUM = 12;
  P_HEARTBEAT=13;
  P_VERSION=14;
  P_CACHE=15;
  P_ASSIGN_COOWNER=16;
  P_SUCCESS_RESPONSE=17;
  P_ERROR_RESPONSE=18;
  P_MIGRATE=19;
  P_BULK_UPLOAD=21;
  P_BULK_DOWNLOAD=22;
}

message Meta {
  AtlasOperation op = 1;
  uint32 chunk_seq = 2;
  uint32 total_chunks = 3;
  uint64 length=4;
}

message BigBangData {
  FileSystemRecord fs_record=1;
  repeated Inode inode=2;
  PodMappingsPage pod_mapping_page=3;
  XentriesPage xentries_page=4;
  DirectoryEntryPage directory_entery_page=5;
}

message ArmageddonData {
  FileSystemRecord fs_record=1;
  repeated uint64 page_ids=2;
}

message MkDirPayload {
  Inode new_inode=1;
  DirectoryEntry directory_entery=2;
  Inode parent_inode=3;
  DirectoryEntry directory_entery_parent=4; 
  Inode xentires_inode=5;
  XentryMapping xentry_mapping=6;
  Inode pod_mapping_inode=7;
  PodMapping pods_mapping=8;
}

message RmDirPayload{
  repeated uint64 pages=1;
  Inode inode=2 ; // parent inode
  DirectoryEntry directory_entery=3;
  Inode xentires_inode=4;
  repeated XentryMapping xentry_mapping=5;
  Inode pod_mapping_inode=6;
  repeated PodMapping pods_mapping=7;
  
}

message createFilePayload {
  Inode new_inode=1;
  Inode parent_inode=3;
  DirectoryEntry directory_entery_parent=4; 
  Inode xentires_inode=5;
  XentryMapping xentry_mapping=6;
  Inode pod_mapping_inode=7;
  PodMapping pods_mapping=8;
}

message RmFilePayload{
  repeated uint64 pages=1;
  Inode inode=2 ; // parent inode
  DirectoryEntry directory_entery=3;
  Inode xentires_inode=4;
  repeated XentryMapping xentry_mapping=5;
  Inode pod_mapping_inode=6;
  repeated PodMapping pods_mapping=7;
}


message pokePayload {
  Inode parent_file_inode=1; 
  bytes data=2;
  uint64 page_no=3;
  uint64 length =4;
  uint64 offset =5;
  Inode pod_mapping_inode=6;
  PodMapping pods_mapping=7;
}

message renamePayload{
  Inode inode=1;
  DirectoryEntry directory_entery=2;
}

message MovePayload{
  Inode source_parent_directory_inode =1;
  DirectoryEntry source_parent_directory=2;
  Inode destination_parent_directory_inode =3;
  DirectoryEntry destination_parent_directory=4;
}

message peekPayload {
  uint64 page_no=1;
  uint64 length =2;
  uint64 offset =3;
}

message Packet {
  Meta meta = 1;
  bytes data=2;
}

message CachePayload {
  repeated uint64 pages =1;
}

message assignCoownerPayload{
   repeated Inode inode = 1;
}

message HeartbeatPayload {
  string pubkey =1 ;
  string signature =2;
  string message =3;
}

message MigrationPayload {
    GlobalCatalogPage catalog=1;
    FileSystemRecord filesystems = 2;
    PodMappingsPage pod_mappings = 3;  
    Inode pod_mapping_inode = 4;
    Inode root_inode =5;        
}

message BulkPokePayload {
  Inode parent_file_inode=1; 
  repeated uint64 page_no=2;
  Inode pod_mapping_inode=3;
  PodMapping pods_mapping=4;
}


message BulkUploadPayload {
  repeated string pods =1;
  repeated string pod_ip = 2;
  BulkPokePayload bulk_poke_payload =3;
  string session_id =4;
  uint64 file_size_bytes = 5;
  string file_hash = 6;
  uint64 start_timestamp = 7;
  string pubkey =8;
}

message BulkPeekPayload {
  repeated uint64 pages=1;
  repeated uint64 length =2;
  repeated uint64 offset =3;
}

message BulkDownloadPayload {
  BulkPeekPayload payload =1;
  string session_id =2;
  string pubkey =3;
}

