syntax = "proto3";
import "metadata.proto";

enum AtlasOperation {
  HANDSHAKE = 0;
  P_BIGBANG = 1;
  P_ARMAGEDDON = 2;
  P_OPENRW = 3;
  P_PEEK = 4;
  P_POKE = 5;
  P_RM = 6;
  P_MKDIR = 7;
  P_RMDIR = 8;
  P_RENAME = 9;
  P_COPY = 10;
  P_MOVE = 11;
}

message Meta {
  AtlasOperation op = 1;
  uint32 chunk_seq = 2;
  uint32 total_chunks = 3;
}

message BigBangData {
  FileSystemRecord fs_record=1;
  Inode inode=2;
}

message ArmageddonData {
  FileSystemRecord fs_record=1;
}

message Packet {
  Meta meta = 1;
  bytes data=2;
}